#ifndef __CONSTANTS__H
#define __CONSTANTS__H

#define QUEUE_SIZE 10
#define BUFFER_SIZE 32

#define SECOND 1000

#define NO_WAIT 0U
#define MSG_PRIO 0U

#define DEBOUNCE_TICKS 300U

#define SPEED_INCR 5 // m/s
#define MAX_SPEED 60 // m/s

#define TRACK_MANAGER_GAIN 10
#define TRACK_MANAGER_PERIOD 50 // ms
#define TRACK_CENTER_REFERENCE -0.0358
#define TRACK_LEFT_REFERENCE -2.5

#define OBSTACLE_WARNING_DISTANCE 25

#endif